version: "3"
services:
  api-min:
    profiles: ['prod']
    image: ghcr.io/wolftsao/hello-api:min
    ports:
      - 8080:8080
    build: .
  
  api-dev:
    profiles: ['dev']
    image: ghcr.io/wolftsao/hello-api:dev
    ports:
      - 8080:8080
    build:
      context: .
      target: dev